services:
  # db migration container
  postgres_migrator:
    image: flsoller/hour-tracker-migration-runner:${TAG}
    ports:
      - '5420:5420'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - appnetwork

  # db migration container
  postgres_tests:
    image: postgres:16.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app_integration_tests
    ports:
      - '5433:5432'
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
