services:
  # db container for dev env
  postgres:
    image: postgres:16.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app_db_dev
    ports:
      - '5432:5432'
    networks:
      - appnetwork
    volumes:
      - postgres-db:/var/lib/postgresql/data

  # db container for local integration test runs
  postgres_testing:
    image: postgres:16.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app_integration_tests
    ports:
      - '5433:5432'

  # db migration container
  postgres_migrator:
    build:
      context: .
      dockerfile: ./apps/db-migrator/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/app_db_dev
      - DEV_OR_INTEGRATION_USE=true
    ports:
      - '5420:5420'
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge

volumes:
  postgres-db:
    driver: local
