services:
  # db migration container
  postgres_migrator:
    image: flsoller/hour-tracker-migration-runner:${TAG}
    ports:
      - '5420:5420'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
