services:
  # db container for dev env
  postgres:
    image: postgres:16.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app_db_dev
    ports:
      - '5432:5432'
    networks:
      - appnetwork
    volumes:
      - postgres-db:/var/lib/postgresql/data

networks:
  appnetwork:
    driver: bridge

volumes:
  postgres-db:
    driver: local
