version: '3.8'
services:
  web:
    build: ./frontend-web/
    environment:
      - NODE_ENV=development
    ports:
      - '4200:4200'
    volumes:
      - './frontend-web:/app'
      - /app/node_modules
    networks:
      - appnetwork
    depends_on:
      - api

  api:
    restart: unless-stopped
    build: ./api/
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/app_db_dev?schema=public
    ports:
      - '5000:5000'
    volumes:
      - './api:/app'
      - /app/node_modules
    networks:
      - appnetwork
    depends_on:
      - postgres

  postgres:
    image: postgres:13.4
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app_db_dev
    ports:
      - '5432:5432'
    networks:
      - appnetwork
    volumes:
      - postgres-db:/var/lib/postgresql/data

networks:
  appnetwork:
    driver: bridge

volumes:
  postgres-db:
    driver: local
