version: '3'
services:
  angular:
    # image: flsoller/angular-app
    build: ./frontend/
    ports:
      - '4200:4200'
    volumes:
      - './frontend:/app'
      - /app/node_modules
    networks:
      - appnetwork
    depends_on:
      - api

  api:
    # image: flsoller/api-server
    restart: unless-stopped
    build: ./api/
    ports:
      - '5000:5000'
    env_file: ./api/.env
    volumes:
      - './api:/app'
      - /app/node_modules
    networks:
      - appnetwork
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4-focal
    ports:
      - '27017:27017'
    networks:
      - appnetwork
    volumes:
      - mongo-db:/data/db

networks:
  appnetwork:
    driver: bridge

volumes:
  mongo-db:
    driver: local
