version: '3.8'
services:
  web:
    build: ./frontend/
    ports:
      - '4200:4200'
    volumes:
      - './frontend:/app'
      - /app/node_modules
    networks:
      - appnetwork
    depends_on:
      - api

  api:
    restart: unless-stopped
    build: ./api/
    environment:
      - NODE_ENV=development
      - PORT=5000
    ports:
      - '5000:5000'
    env_file: ./api/.env
    volumes:
      - './api:/app'
      - /app/node_modules
    networks:
      - appnetwork
    depends_on:
      - postgres

  postgres:
    image: postgres:13.4
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app-db
    ports:
      - '5432:5432'
    networks:
      - appnetwork
    volumes:
      - postgres-db:/data/db

networks:
  appnetwork:
    driver: bridge

volumes:
  postgres-db:
    driver: local
