name: Organization_Manager

on:
  workflow_dispatch:
    inputs:
      organization_name:
        description: "The name of the organization"
        required: true
        type: string

jobs:
  call_org_manager:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}
