export const ENVIRONMENT_PARAMS = {
  DATABASE_URL_KEY: "HOUR_TRACKER_DATABASE_URL",
  JWT_SECRET: "HOUR_TRACKER_JWT_SECRET",
  AUTHORIZED_PARTY: "HOUR_TRACKER_AUTHORIZED_PARTY",
  API_DOMAIN_NAME: "HOUR_TRACKER_API_DOMAIN_NAME",
  API_DOMAIN_CERT_ARN: "HOUR_TRACKER_API_DOMAIN_CERT_ARN",
  HOUR_TRACKER_API_CORS_ORIGIN: "HOUR_TRACKER_API_CORS_ORIGIN",
  NEW_RELIC_ACCOUNT_ID: "NEW_RELIC_ACCOUNT_ID",
  NEW_RELIC_LICENSE_KEY: "NEW_RELIC_LICENSE_KEY",
};
