export const ENVIRONMENT_PARAMS = {
  DATABASE_URL_KEY: "HOUR_TRACKER_DATABASE_URL",
  JWT_SECRET: "HOUR_TRACKER_JWT_SECRET",
  API_DOMAIN_NAME: "HOUR_TRACKER_API_DOMAIN_NAME",
  API_DOMAIN_CERT_ARN: "HOUR_TRACKER_API_DOMAIN_CERT_ARN",
};
