export const DEFAULT_INSTRUMENTATION_CONFIG = {
  NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS: "true",
  NEW_RELIC_LAMBDA_EXTENSION_ENABLED: "true",
  NEW_RELIC_DATA_COLLECTION_TIMEOUT: "10s",
  NEW_RELIC_IGNORE_EXTENSION_CHECKS: "all",
  NEW_RELIC_NO_CONFIG_FILE: "true",
};
