name: Task
description: Describe a task or feature to implement
labels: ["development"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the task, goal, or feature you want to implement
      placeholder: As a user, I want to...
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: List the requirements that must be met for this task to be considered complete
      placeholder: |
        - [ ] Requirement 1
        - [ ] Requirement 2
        - [ ] Requirement 3
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references
    validations:
      required: false
