name: Docker Image CI

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker build web
        run: docker build -f ./frontend/Dockerfile --tag web-frontend:$(date +%s) --build-arg BUILD_CONTEXT=frontend .
      - name: docker build api prod
        run: docker build -f ./api/Dockerfile.prod --tag api:$(date +%s) --build-arg BUILD_CONTEXT=api .
      - name: docker build api dev
        run: docker build -f ./api/Dockerfile --tag api:$(date +%s) --build-arg BUILD_CONTEXT=api .
