name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker build web
        run: docker build -f ./frontend/Dockerfile --tag web-frontend:$(date +%s) --build-arg BUILD_CONTEXT=frontend .
      - name: docker build api
        run: docker build -f ./api/Dockerfile --tag api:$(date +%s) --build-arg BUILD_CONTEXT=api .
