name: Tests

on:
  push:
    branches: '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker
        run: |
          echo ---building and starting up docker---
          docker-compose -f docker-compose.dev.yml up -d
          echo ---containers are running---
      - name: Run api integration tests
        run: |
          echo ---running api tests---
          docker-compose -f docker-compose.dev.yml exec -T api yarn workspace hour-tracker-api test
      - name: Run frontend tests
        run: |
          echo ---running frontend tests---
          docker-compose -f docker-compose.dev.yml exec -T web yarn workspace hour-tracker-frontend test
