name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: cd ./api && yarn install
      - name: Run tests
        run: cd ./api && yarn test-ci:integration
