name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker
        run: |
          echo ---building and starting up docker---
          docker-compose -f docker-compose.dev.yml up -d
          echo ---containers are running---
      - name: Run tests
        run: |
          echo ---running tests---
          docker-compose -f docker-compose.dev.yml exec api yarn test
